cacheFolder: .yarn/cache

checksumBehavior: throw

compressionLevel: 9

defaultLanguageName: node

defaultProtocol: "npm:"

enableColors: true

enableGlobalCache: true

enableHyperlinks: true

enableMessageNames: true

enableMirror: true

enableProgressBars: true

enableStrictSsl: true

enableTelemetry: true

globalFolder: .yarn/global

httpRetry: 3

httpTimeout: 60000

lockfileFilename: yarn.lock

nodeLinker: node-modules

npmAuditRegistry: "https://npm.pkg.github.com"

npmPublishAccess: restricted

npmPublishRegistry: "https://npm.pkg.github.com"

npmRegistryServer: "https://registry.npmjs.com"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-stage.cjs
    spec: "@yarnpkg/plugin-stage"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

telemetryInterval: 7

yarnPath: .yarn/releases/yarn-3.2.0.cjs
