yarnPath: .yarn/releases/yarn-3.1.1.cjs
cacheFolder: .yarn/cache
compressionLevel: 9
defaultLanguageName: "node"
defaultProtocol: "npm:"
enableColors: true
enableHyperlinks: true
enableGlobalCache: true
enableProgressBars: true
enableMessageNames: true
enableMirror: true
enableStrictSsl: true
enableTelemetry: true
checksumBehavior: "throw"
lockfileFilename: "yarn.lock"
globalFolder: .yarn/global
httpRetry: 3
httpTimeout: 60000
nodeLinker: "node-modules"
npmRegistryServer: "https://registry.npmjs.com"
npmAuditRegistry: "https://npm.pkg.github.com"
npmPublishRegistry: "https://npm.pkg.github.com"
npmPublishAccess: "restricted"
telemetryInterval: 7
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
